#!/usr/bin/env python3
"""Script to get the email(s) for any GitHub username or project"""

import re
import sys
import json
import urllib.request

USER_RE = re.compile(
    r'(?:https?://)?(?:github\.com/)?([\w-]+)(?:[/?].*)?'
)


if __name__ == '__main__':
    if len(sys.argv) >= 2:
        who = sys.argv[1]
    else:
        who = input()

    match = USER_RE.match(who)
    if not match:
        sys.stderr.write('Failed to match username on given input.\n')
        exit(1)

    json = json.loads(urllib.request.urlopen(
        'https://api.github.com/users/{}/events/public'.format(match.group(1))
    ).read().decode('utf-8'))

    emails = set()
    for item in json:
        if item['type'] == 'PushEvent':
            for commit in item['payload']['commits']:
                emails.add(commit['author']['email'].lower())

    for email in sorted(emails):
        print(email)
